/* Verilog module instantiation template generated by SCUBA Diamond Version 3.7.0.96.1 */
/* Module Version: 1.2 */
/* Sat Apr 08 14:16:46 2017 */

/* parameterized module instance */
SPI __ (.wb_clk_i( ), .wb_rst_i( ), .wb_cyc_i( ), .wb_stb_i( ), 
    .wb_we_i( ), .wb_adr_i( ), .wb_dat_i( ), .wb_dat_o( ), .wb_ack_o( ), 
    .spi_clk( ), .spi_miso( ), .spi_mosi( ), .spi_scsn( ), .spi_irq( ));
