/* Verilog module instantiation template generated by SCUBA Diamond Version 3.7.0.96.1 */
/* Module Version: 5.8 */
/* Thu May 04 15:21:19 2017 */

/* parameterized module instance */
FIFO __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ), .AlmostEmpty( ), 
    .AlmostFull( ));
