/* Verilog netlist generated by SCUBA Diamond Version 3.7.0.96.1 */
/* Module Version: 5.8 */
/* C:\Program Files\LSCC\diamond\3.7\ispfpga\bin\nt\scuba.exe -w -n FIFO -lang verilog -synth synplify -bus_exp 7 -bb -arch xo2c00 -type ebfifo -depth 8 -width 24 -rwidth 24 -no_enable -pe 1 -pf 7 -sync_reset  */
/* Thu May 04 15:21:19 2017 */


`timescale 1 ns / 1 ps
module FIFO (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, Q, 
    Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [23:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [23:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire scuba_vhi;
    wire Empty_int;
    wire Full_int;
    wire scuba_vlo;

    defparam FIFO_0_1.FULLPOINTER1 = "0b00000001110000" ;
    defparam FIFO_0_1.FULLPOINTER = "0b00000010000000" ;
    defparam FIFO_0_1.AFPOINTER1 = "0b00000001100000" ;
    defparam FIFO_0_1.AFPOINTER = "0b00000001110000" ;
    defparam FIFO_0_1.AEPOINTER1 = "0b00000000100000" ;
    defparam FIFO_0_1.AEPOINTER = "0b00000000010000" ;
    defparam FIFO_0_1.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam FIFO_0_1.GSR = "DISABLED" ;
    defparam FIFO_0_1.RESETMODE = "SYNC" ;
    defparam FIFO_0_1.REGMODE = "NOREG" ;
    defparam FIFO_0_1.CSDECODE_R = "0b11" ;
    defparam FIFO_0_1.CSDECODE_W = "0b11" ;
    defparam FIFO_0_1.DATA_WIDTH_R = 18 ;
    defparam FIFO_0_1.DATA_WIDTH_W = 18 ;
    FIFO8KB FIFO_0_1 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), .DI3(Data[3]), 
        .DI4(Data[4]), .DI5(Data[5]), .DI6(Data[6]), .DI7(Data[7]), .DI8(Data[8]), 
        .DI9(Data[9]), .DI10(Data[10]), .DI11(Data[11]), .DI12(Data[12]), 
        .DI13(Data[13]), .DI14(Data[14]), .DI15(Data[15]), .DI16(Data[16]), 
        .DI17(Data[17]), .CSW0(scuba_vhi), .CSW1(scuba_vhi), .CSR0(scuba_vhi), 
        .CSR1(scuba_vhi), .FULLI(Full_int), .EMPTYI(Empty_int), .WE(WrEn), 
        .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), .RST(Reset), 
        .RPRST(RPReset), .DO0(Q[9]), .DO1(Q[10]), .DO2(Q[11]), .DO3(Q[12]), 
        .DO4(Q[13]), .DO5(Q[14]), .DO6(Q[15]), .DO7(Q[16]), .DO8(Q[17]), 
        .DO9(Q[0]), .DO10(Q[1]), .DO11(Q[2]), .DO12(Q[3]), .DO13(Q[4]), 
        .DO14(Q[5]), .DO15(Q[6]), .DO16(Q[7]), .DO17(Q[8]), .EF(Empty_int), 
        .AEF(AlmostEmpty), .AFF(AlmostFull), .FF(Full_int));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam FIFO_1_0.FULLPOINTER1 = "0b00000000000000" ;
    defparam FIFO_1_0.FULLPOINTER = "0b11111111110000" ;
    defparam FIFO_1_0.AFPOINTER1 = "0b00000000000000" ;
    defparam FIFO_1_0.AFPOINTER = "0b11111111110000" ;
    defparam FIFO_1_0.AEPOINTER1 = "0b00000000000000" ;
    defparam FIFO_1_0.AEPOINTER = "0b11111111110000" ;
    defparam FIFO_1_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam FIFO_1_0.GSR = "DISABLED" ;
    defparam FIFO_1_0.RESETMODE = "SYNC" ;
    defparam FIFO_1_0.REGMODE = "NOREG" ;
    defparam FIFO_1_0.CSDECODE_R = "0b11" ;
    defparam FIFO_1_0.CSDECODE_W = "0b11" ;
    defparam FIFO_1_0.DATA_WIDTH_R = 18 ;
    defparam FIFO_1_0.DATA_WIDTH_W = 18 ;
    FIFO8KB FIFO_1_0 (.DI0(Data[18]), .DI1(Data[19]), .DI2(Data[20]), .DI3(Data[21]), 
        .DI4(Data[22]), .DI5(Data[23]), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(scuba_vhi), 
        .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(), .DO1(), .DO2(), .DO3(), .DO4(), 
        .DO5(), .DO6(), .DO7(), .DO8(), .DO9(Q[18]), .DO10(Q[19]), .DO11(Q[20]), 
        .DO12(Q[21]), .DO13(Q[22]), .DO14(Q[23]), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    assign Empty = Empty_int;
    assign Full = Full_int;


    // exemplar begin
    // exemplar end

endmodule
