/* Verilog module instantiation template generated by SCUBA Diamond Version 3.7.0.96.1 */
/* Module Version: 6.5 */
/* Wed Mar 15 10:01:12 2017 */

/* parameterized module instance */
RAM __ (.WrAddress( ), .RdAddress( ), .Data( ), .WE( ), .RdClock( ), 
    .RdClockEn( ), .Reset( ), .WrClock( ), .WrClockEn( ), .Q( ));
